export const MASTER = {
  page: "master-data-page",
  tabDocTemplates: "master-tab-doc-templates",
  tabQcTemplates: "master-tab-qc-templates",
  tabHealth: "master-tab-health",
  tabReference: "master-tab-reference",
  tabBuildPolicy: "master-tab-build-policy",
  tabKprProducts: "master-tab-kpr-products",
  kprPanel: "master-kpr-products-panel",
  kprAddBtn: "master-kpr-add-btn",
  kprRow: "master-kpr-row",
  kprEmpty: "master-kpr-empty",
  kprShowInactive: "master-kpr-show-inactive",
  kprDialog: "master-kpr-dialog",
  kprFormBank: "master-kpr-form-bank",
  kprFormName: "master-kpr-form-name",
  kprFormTenors: "master-kpr-form-tenors",
  kprFormRate: "master-kpr-form-rate",
  kprFormFixedYears: "master-kpr-form-fixed-years",
  kprFormFloating: "master-kpr-form-floating",
  kprFormMinDp: "master-kpr-form-min-dp",
  kprFormNotes: "master-kpr-form-notes",
  kprFormActive: "master-kpr-form-active",
  kprSubmit: "master-kpr-submit",
  kprEditBtn: "master-kpr-edit-btn",
  kprArchiveBtn: "master-kpr-archive-btn",
  kprImportFile: "master-kpr-import-file",
  kprImportBtn: "master-kpr-import-btn",
  kprTemplateBtn: "master-kpr-template-btn",
  kprImportReport: "master-kpr-import-report",
  kprImportPreview: "master-kpr-import-preview",
  kprImportPreviewRow: "master-kpr-import-preview-row",
  kprImportConfirm: "master-kpr-import-confirm",
  kprImportCancel: "master-kpr-import-cancel",
  buildPolicyPanel: "master-build-policy-panel",
  policyGeo: "master-policy-geo-required",
  policyCamera: "master-policy-camera-only",
  policyNoteChars: "master-policy-note-chars",
  policyAccuracy: "master-policy-accuracy",
  policySave: "master-policy-save",
  refPanel: "master-reference-panel",
  refSearch: "master-reference-search",
  refGroupRow: "master-reference-group",
  docAddBtn: "master-doc-add-btn",
  docRow: "master-doc-row",
  docFormCode: "master-doc-form-code",
  docFormName: "master-doc-form-name",
  docFormContent: "master-doc-form-content",
  docSubmit: "master-doc-submit",
  docEditBtn: "master-doc-edit-btn",
  docArchiveBtn: "master-doc-archive-btn",
  qcAddBtn: "master-qc-add-btn",
  qcRow: "master-qc-row",
  qcFormCode: "master-qc-form-code",
  qcFormName: "master-qc-form-name",
  qcFormCategory: "master-qc-form-category",
  qcItemInput: "master-qc-item-input",
  qcItemAdd: "master-qc-item-add",
  qcSubmit: "master-qc-submit",
  qcEditBtn: "master-qc-edit-btn",
  qcArchiveBtn: "master-qc-archive-btn",
  healthRefresh: "master-health-refresh",
  phoneHealth: "master-phone-health",
  phoneNormalize: "master-phone-normalize-btn",
  phoneClean: "master-phone-clean",
  phoneRow: "master-phone-row",
  phoneFixBtn: "master-phone-fix-btn",
  phoneFixDialog: "master-phone-fix-dialog",
  phoneFixItem: "master-phone-fix-item",
  phoneFixInput: "master-phone-fix-input",
  phoneFixSave: "master-phone-fix-save",
  phoneFixClear: "master-phone-fix-clear",
  phoneFixLink: "master-phone-fix-link",
  healthStale: "master-health-stale",
  healthInvalid: "master-health-invalid",
};

export const AUDIT = {
  page: "audit-logs-page",
  row: "audit-log-row",
  filterResource: "audit-filter-resource",
  filterAction: "audit-filter-action",
  refresh: "audit-refresh",
  // Fase 39b — riwayat migrasi/backfill data + keadaan sekarang (bukti US-39-5)
  migrationPanel: "migration-runs-panel",
  migrationState: "migration-state",
  migrationRow: "migration-run-row",
};

export const PROJECT_EDIT = {
  editBtn: "project-edit-btn",
  formName: "project-edit-name",
  formCode: "project-edit-code",
  formLocation: "project-edit-location",
  formMarketingOffice: "project-edit-marketing-office",
  formStatus: "project-edit-status",
  submit: "project-edit-submit",
  unitEditBtn: "unit-edit-btn",
  unitFormType: "unit-edit-type",
  unitFormPrice: "unit-edit-price",
  // Fase 28b — spesifikasi kavling jadi field nyata
  unitFormLuasTanah: "unit-edit-luas-tanah",
  unitFormLuasBangunan: "unit-edit-luas-bangunan",
  unitFormOrientation: "unit-edit-orientation",
  unitFormCorner: "unit-edit-corner",
  unitSubmit: "unit-edit-submit",
};
