// Customer Portal (EPIC M1) testIds.
export const PORTAL = {
  loginPage: "portal-login-page",
  identifierInput: "portal-identifier-input",
  requestOtpBtn: "portal-request-otp-button",
  otpInput: "portal-otp-input",
  verifyOtpBtn: "portal-verify-otp-button",
  devCode: "portal-dev-code",
  app: "portal-app",
  logoutBtn: "portal-logout-button",
  tabOverview: "portal-tab-overview",
  tabPayments: "portal-tab-payments",
  tabProgress: "portal-tab-progress",
  tabDocuments: "portal-tab-documents",
  tabComplaints: "portal-tab-complaints",
  overviewPanel: "portal-overview-panel",
  paymentsPanel: "portal-payments-panel",
  progressPanel: "portal-progress-panel",
  documentsPanel: "portal-documents-panel",
  complaintsPanel: "portal-complaints-panel",
  paymentRow: "portal-payment-row",
  documentRow: "portal-document-row",
  complaintRow: "portal-complaint-row",
  complaintAddBtn: "portal-complaint-add-button",
  complaintSubmit: "portal-complaint-submit",
  // Fase 28b — peta kavling & foto progres untuk pembeli
  tabPlan: "portal-tab-plan",
  // Jadwal angsuran KPR pembeli (fixed → floating) sesudah SP3K
  tabKpr: "portal-tab-kpr",
  kprPanel: "portal-kpr-panel",
  kprCard: "portal-kpr-card",
  kprEmpty: "portal-kpr-empty",
  kprPending: "portal-kpr-pending",
  kprScheduleRow: "portal-kpr-schedule-row",
  planPanel: "portal-plan-panel",
  myUnitCard: "portal-my-unit-card",
  progressPhotos: "portal-progress-photos",
  buildMilestones: "portal-build-milestones",
  repairs: "portal-repair-evidence",
};
